language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("DecisionTrees")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("DecisionTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
