language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  email: false

codecov: true

coveralls: true
